require('lspconfig').pyright.setup{}
require('lspconfig').gopls.setup{}
require('settings')
 require('mappings')
 require('packer-config')
 require('colorschemes-config.onedark')
 require('nvim-tree-config')
 require('lsp-config.language-servers')
 require('lsp-config.nvim-cmp')
 require('mason-config')
